/*
 Cropper v4.0.0
 https://github.com/fengyuanchen/cropper

 Copyright (c) 2014-2018 Chen Fengyuan
 Released under the MIT license

 Date: 2018-04-01T06:27:27.267Z
*/
Module.define("cropper",["jquery","cropper.css"],function(h){(function(G,g){"object"===typeof exports&&"undefined"!==typeof h?g(require("jquery")):"function"===typeof define&&define.amd?define(["jquery"],g):g(G.jQuery)})(this,function(h){function g(a){return"number"===typeof a&&!ha(a)}function k(a){return"undefined"===typeof a}function b(a){return"object"===("undefined"===typeof a?"undefined":ia(a))&&null!==a}function f(a){if(!b(a))return!1;try{var d=a.constructor,e=d.prototype;return d&&e&&ja.call(e,
"isPrototypeOf")}catch(m){return!1}}function q(a){return"function"===typeof a}function n(a,d){if(a&&q(d))if(Array.isArray(a)||g(a.length)){var e=a.length,m=void 0;for(m=0;m<e&&!1!==d.call(a,a[m],m,a);m+=1);}else b(a)&&Object.keys(a).forEach(function(e){d.call(a,a[e],e,a)});return a}function A(a){var d=1<arguments.length&&void 0!==arguments[1]?arguments[1]:1E11;return ka.test(a)?Math.round(a*d)/d:a}function v(a,d){var e=a.style;n(d,function(a,d){la.test(d)&&g(a)&&(a+="px");e[d]=a})}function z(a,d){return a.classList?
a.classList.contains(d):-1<a.className.indexOf(d)}function t(a,d){if(d)if(g(a.length))n(a,function(a){t(a,d)});else if(a.classList)a.classList.add(d);else{var e=a.className.trim();e?0>e.indexOf(d)&&(a.className=e+" "+d):a.className=d}}function C(a,d){d&&(g(a.length)?n(a,function(a){C(a,d)}):a.classList?a.classList.remove(d):0<=a.className.indexOf(d)&&(a.className=a.className.replace(d,"")))}function I(a,d,e){d&&(g(a.length)?n(a,function(a){I(a,d,e)}):e?t(a,d):C(a,d))}function y(a){return a.replace(ma,
"$1-$2").toLowerCase()}function L(a,d){return b(a[d])?a[d]:a.dataset?a.dataset[d]:a.getAttribute("data-"+y(d))}function M(a,d,e){b(e)?a[d]=e:a.dataset?a.dataset[d]=e:a.setAttribute("data-"+y(d),e)}function G(a,d){if(b(a[d]))try{delete a[d]}catch(e){a[d]=void 0}else if(a.dataset)try{delete a.dataset[d]}catch(e){a.dataset[d]=void 0}else a.removeAttribute("data-"+y(d))}function H(a,d,e){var m=3<arguments.length&&void 0!==arguments[3]?arguments[3]:{},u=e;d.trim().split(W).forEach(function(d){if(!X){var r=
a.listeners;r&&r[d]&&r[d][e]&&(u=r[d][e],delete r[d][e],0===Object.keys(r[d]).length&&delete r[d],0===Object.keys(r).length&&delete a.listeners)}a.removeEventListener(d,u,m)})}function F(a,d,e){var m=3<arguments.length&&void 0!==arguments[3]?arguments[3]:{},u=e;d.trim().split(W).forEach(function(d){if(m.once&&!X){var r=a.listeners,c=void 0===r?{}:r;u=function(){for(var r=arguments.length,b=Array(r),l=0;l<r;l++)b[l]=arguments[l];delete c[d][e];a.removeEventListener(d,u,m);e.apply(a,b)};c[d]||(c[d]=
{});c[d][e]&&a.removeEventListener(d,c[d][e],m);c[d][e]=u;a.listeners=c}a.addEventListener(d,u,m)})}function K(a,d,e){if(q(Event)&&q(CustomEvent))var m=new CustomEvent(d,{detail:e,bubbles:!0,cancelable:!0});else m=document.createEvent("CustomEvent"),m.initCustomEvent(d,!0,!0,e);return a.dispatchEvent(m)}function N(a){a=a.getBoundingClientRect();return{left:a.left+(window.pageXOffset-document.documentElement.clientLeft),top:a.top+(window.pageYOffset-document.documentElement.clientTop)}}function Q(a){return(a=
a.match(na))&&(a[1]!==V.protocol||a[2]!==V.hostname||a[3]!==V.port)}function R(a){var d="timestamp\x3d"+(new Date).getTime();return a+(-1===a.indexOf("?")?"?":"\x26")+d}function O(a){var d=a.rotate,e=a.scaleX,m=a.scaleY,u=a.translateX;a=a.translateY;var r=[];g(u)&&0!==u&&r.push("translateX("+u+"px)");g(a)&&0!==a&&r.push("translateY("+a+"px)");g(d)&&0!==d&&r.push("rotate("+d+"deg)");g(e)&&1!==e&&r.push("scaleX("+e+")");g(m)&&1!==m&&r.push("scaleY("+m+")");d=r.length?r.join(" "):"none";return{WebkitTransform:d,
msTransform:d,transform:d}}function S(a){var d=B({},a),e=[];n(a,function(a,u){delete d[u];n(d,function(d){var m=Math.abs(a.startX-d.startX),u=Math.abs(a.startY-d.startY),r=Math.abs(a.endX-d.endX);d=Math.abs(a.endY-d.endY);m=Math.sqrt(m*m+u*u);e.push((Math.sqrt(r*r+d*d)-m)/m)})});e.sort(function(a,d){return Math.abs(a)<Math.abs(d)});return e[0]}function c(a,d){var e=a.pageX;a=a.pageY;var m={endX:e,endY:a};return d?m:B({startX:e,startY:a},m)}function l(a){var d=0,e=0,m=0;n(a,function(a){var u=a.startY;
d+=a.startX;e+=u;m+=1});d/=m;e/=m;return{pageX:d,pageY:e}}function p(a){var d=a.aspectRatio,e=a.height,m=a.width,u=1<arguments.length&&void 0!==arguments[1]?arguments[1]:"contain",r=function(a){return oa(a)&&0<a};r(m)&&r(e)?(r=e*d,"contain"===u&&r>m||"cover"===u&&r<m?e=m/d:m=e*d):r(m)?e=m/d:r(e)&&(m=e*d);return{width:m,height:e}}function E(a,d,e,m){var u=d.aspectRatio,r=d.naturalWidth,c=d.naturalHeight,b=d.rotate;b=void 0===b?0:b;var l=d.scaleX;l=void 0===l?1:l;d=d.scaleY;d=void 0===d?1:d;var f=e.aspectRatio,
P=e.naturalWidth,n=e.naturalHeight;e=m.fillColor;e=void 0===e?"transparent":e;var h=m.imageSmoothingEnabled;h=void 0===h?!0:h;var k=m.imageSmoothingQuality;k=void 0===k?"low":k;var g=m.maxWidth,q=void 0===g?Infinity:g;g=m.maxHeight;var v=void 0===g?Infinity:g;g=m.minWidth;var E=void 0===g?0:g;m=m.minHeight;var t=void 0===m?0:m;m=document.createElement("canvas");g=m.getContext("2d");var x=p({aspectRatio:f,width:q,height:v});f=p({aspectRatio:f,width:E,height:t},"cover");P=Math.min(x.width,Math.max(f.width,
P));n=Math.min(x.height,Math.max(f.height,n));f=p({aspectRatio:u,width:q,height:v});u=p({aspectRatio:u,width:E,height:t},"cover");r=Math.min(f.width,Math.max(u.width,r));c=Math.min(f.height,Math.max(u.height,c));c=[-r/2,-c/2,r,c];m.width=A(P);m.height=A(n);g.fillStyle=e;g.fillRect(0,0,P,n);g.save();g.translate(P/2,n/2);g.rotate(b*Math.PI/180);g.scale(l,d);g.imageSmoothingEnabled=h;g.imageSmoothingQuality=k;g.drawImage.apply(g,[a].concat(Y(c.map(function(a){return Math.floor(A(a))}))));g.restore();
return m}function D(a){a=a.replace(pa,"");var d=atob(a);a=new ArrayBuffer(d.length);var e=new Uint8Array(a);n(e,function(a,u){e[u]=d.charCodeAt(u)});return a}function Z(a,d){a=new Uint8Array(a);var e="";n(a,function(a){e+=aa(a)});return"data:"+d+";base64,"+btoa(e)}h=jQuery;var ba="undefined"!==typeof window,J=ba?window:{},ca=J.PointerEvent?"pointerdown":"touchstart mousedown",da=J.PointerEvent?"pointermove":"touchmove mousemove",ea=J.PointerEvent?"pointerup pointercancel":"touchend touchcancel mouseup",
qa=/^(?:e|w|s|n|se|sw|ne|nw|all|crop|move|zoom)$/,ra=/^data:/,sa=/^data:image\/jpeg;base64,/,ta=/^(?:img|canvas)$/i,fa={viewMode:0,dragMode:"crop",aspectRatio:NaN,data:null,preview:"",responsive:!0,restore:!0,checkCrossOrigin:!0,checkOrientation:!0,modal:!0,guides:!0,center:!0,highlight:!0,background:!0,autoCrop:!0,autoCropArea:.8,movable:!0,rotatable:!0,scalable:!0,zoomable:!0,zoomOnTouch:!0,zoomOnWheel:!0,wheelZoomRatio:.1,cropBoxMovable:!0,cropBoxResizable:!0,toggleDragModeOnDblclick:!0,minCanvasWidth:0,
minCanvasHeight:0,minCropBoxWidth:0,minCropBoxHeight:0,minContainerWidth:200,minContainerHeight:100,ready:null,cropstart:null,cropmove:null,cropend:null,crop:null,zoom:null},ia="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(a){return typeof a}:function(a){return a&&"function"===typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":typeof a},ua=function(){function a(a,e){for(var d=0;d<e.length;d++){var u=e[d];u.enumerable=u.enumerable||!1;u.configurable=!0;"value"in
u&&(u.writable=!0);Object.defineProperty(a,u.key,u)}}return function(d,e,m){e&&a(d.prototype,e);m&&a(d,m);return d}}(),Y=function(a){if(Array.isArray(a)){for(var d=0,e=Array(a.length);d<a.length;d++)e[d]=a[d];return e}return Array.from(a)},ha=Number.isNaN||J.isNaN,ja=Object.prototype.hasOwnProperty,B=Object.assign||function(a){for(var d=arguments.length,e=Array(1<d?d-1:0),m=1;m<d;m++)e[m-1]=arguments[m];b(a)&&0<e.length&&e.forEach(function(d){b(d)&&Object.keys(d).forEach(function(e){a[e]=d[e]})});
return a},ka=/\.\d*(?:0|9){12}\d*$/i,la=/^(?:width|height|left|top|marginLeft|marginTop)$/,ma=/([a-z\d])([A-Z])/g,W=/\s\s*/,X=function(){var a=!1;if(ba){var d=!1,e=function(){},m=Object.defineProperty({},"once",{get:function(){a=!0;return d},set:function(a){d=a}});J.addEventListener("test",e,m);J.removeEventListener("test",e,m)}return a}(),V=J.location,na=/^(https?:)\/\/([^:/?#]+):?(\d*)/i,oa=Number.isFinite||J.isFinite,aa=String.fromCharCode,pa=/^data:.*,/,va=J.Cropper,T=function(){function a(d){var e=
1<arguments.length&&void 0!==arguments[1]?arguments[1]:{};if(!(this instanceof a))throw new TypeError("Cannot call a class as a function");if(!d||!ta.test(d.tagName))throw Error("The first argument is required and must be an \x3cimg\x3e or \x3ccanvas\x3e element.");this.element=d;this.options=B({},fa,f(e)&&e);this.disabled=this.cropped=!1;this.pointers={};this.sizing=this.sized=this.replaced=this.reloading=this.ready=!1;this.init()}ua(a,[{key:"init",value:function(){var a=this.element,e=a.tagName.toLowerCase(),
m=void 0;if(!L(a,"cropper")){M(a,"cropper",this);if("img"===e){this.isImg=!0;this.originalUrl=m=a.getAttribute("src")||"";if(!m)return;m=a.src}else"canvas"===e&&window.HTMLCanvasElement&&(m=a.toDataURL());this.load(m)}}},{key:"load",value:function(a){var d=this;if(a){this.url=a;this.imageData={};var m=this.element,u=this.options;if(u.checkOrientation&&window.ArrayBuffer)if(ra.test(a))sa.test(a)?this.read(D(a)):this.clone();else{var c=new XMLHttpRequest;this.reloading=!0;this.xhr=c;var b=function(){d.reloading=
!1;d.xhr=null};c.ontimeout=b;c.onabort=b;c.onerror=function(){b();d.clone()};c.onload=function(){b();d.read(c.response)};u.checkCrossOrigin&&Q(a)&&m.crossOrigin&&(a=R(a));c.open("get",a);c.responseType="arraybuffer";c.withCredentials="use-credentials"===m.crossOrigin;c.send()}else this.clone()}}},{key:"read",value:function(a){var d=this.options,m=this.imageData;var c=new DataView(a);var r=void 0,b=void 0,l=void 0,f=void 0;if(255===c.getUint8(0)&&216===c.getUint8(1))for(var p=c.byteLength,g=2;g<p;){if(255===
c.getUint8(g)&&225===c.getUint8(g+1)){l=g;break}g+=1}if(l){p=l+10;var n=l+4;g="";for(l=4+n;n<l;n+=1)g+=aa(c.getUint8(n));"Exif"===g&&(l=c.getUint16(p),!(b=18761===l)&&19789!==l||42!==c.getUint16(p+2,b)||(l=c.getUint32(p+4,b),8<=l&&(f=p+l)))}if(f)for(p=c.getUint16(f,b),g=0;g<p;g+=1)if(l=f+12*g+2,274===c.getUint16(l,b)){l+=8;r=c.getUint16(l,b);c.setUint16(l,1,b);break}c=r;r=0;f=b=1;if(1<c){this.url=Z(a,"image/jpeg");r=0;a=b=1;switch(c){case 2:b=-1;break;case 3:r=-180;break;case 4:a=-1;break;case 5:r=
90;a=-1;break;case 6:r=90;break;case 7:r=90;b=-1;break;case 8:r=-90}f=a}d.rotatable&&(m.rotate=r);d.scalable&&(m.scaleX=b,m.scaleY=f);this.clone()}},{key:"clone",value:function(){var a=this.element,e=this.url,m=void 0,c=void 0;this.options.checkCrossOrigin&&Q(e)&&((m=a.crossOrigin)?c=e:(m="anonymous",c=R(e)));this.crossOrigin=m;this.crossOriginUrl=c;var r=document.createElement("img");m&&(r.crossOrigin=m);r.src=c||e;e=this.start.bind(this);m=this.stop.bind(this);this.image=r;this.onStart=e;this.onStop=
m;this.isImg?a.complete?this.timeout=setTimeout(e,0):F(a,"load",e,{once:!0}):(r.onload=e,r.onerror=m,t(r,"cropper-hide"),a.parentNode.insertBefore(r,a.nextSibling))}},{key:"start",value:function(a){var d=this,m=this.isImg?this.element:this.image;a&&(m.onload=null,m.onerror=null);this.sizing=!0;var c=J.navigator&&/(Macintosh|iPhone|iPod|iPad).*AppleWebKit/i.test(J.navigator.userAgent),r=function(a,e){B(d.imageData,{naturalWidth:a,naturalHeight:e,aspectRatio:a/e});d.sizing=!1;d.sized=!0;d.build()};
if(m.naturalWidth&&!c)r(m.naturalWidth,m.naturalHeight);else{var b=document.createElement("img"),l=document.body||document.documentElement;this.sizingImage=b;b.onload=function(){r(b.width,b.height);c||l.removeChild(b)};b.src=m.src;c||(b.style.cssText="left:0;max-height:none!important;max-width:none!important;min-height:0!important;min-width:0!important;opacity:0;position:absolute;top:0;z-index:-1;",l.appendChild(b))}}},{key:"stop",value:function(){var a=this.image;a.onload=null;a.onerror=null;a.parentNode.removeChild(a);
this.image=null}},{key:"build",value:function(){if(this.sized&&!this.ready){var a=this.element,e=this.options,m=this.image,c=a.parentNode,b=document.createElement("div");b.innerHTML='\x3cdiv class\x3d"cropper-container" touch-action\x3d"none"\x3e\x3cdiv class\x3d"cropper-wrap-box"\x3e\x3cdiv class\x3d"cropper-canvas"\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"cropper-drag-box"\x3e\x3c/div\x3e\x3cdiv class\x3d"cropper-crop-box"\x3e\x3cspan class\x3d"cropper-view-box"\x3e\x3c/span\x3e\x3cspan class\x3d"cropper-dashed dashed-h"\x3e\x3c/span\x3e\x3cspan class\x3d"cropper-dashed dashed-v"\x3e\x3c/span\x3e\x3cspan class\x3d"cropper-center"\x3e\x3c/span\x3e\x3cspan class\x3d"cropper-face"\x3e\x3c/span\x3e\x3cspan class\x3d"cropper-line line-e" data-action\x3d"e"\x3e\x3c/span\x3e\x3cspan class\x3d"cropper-line line-n" data-action\x3d"n"\x3e\x3c/span\x3e\x3cspan class\x3d"cropper-line line-w" data-action\x3d"w"\x3e\x3c/span\x3e\x3cspan class\x3d"cropper-line line-s" data-action\x3d"s"\x3e\x3c/span\x3e\x3cspan class\x3d"cropper-point point-e" data-action\x3d"e"\x3e\x3c/span\x3e\x3cspan class\x3d"cropper-point point-n" data-action\x3d"n"\x3e\x3c/span\x3e\x3cspan class\x3d"cropper-point point-w" data-action\x3d"w"\x3e\x3c/span\x3e\x3cspan class\x3d"cropper-point point-s" data-action\x3d"s"\x3e\x3c/span\x3e\x3cspan class\x3d"cropper-point point-ne" data-action\x3d"ne"\x3e\x3c/span\x3e\x3cspan class\x3d"cropper-point point-nw" data-action\x3d"nw"\x3e\x3c/span\x3e\x3cspan class\x3d"cropper-point point-sw" data-action\x3d"sw"\x3e\x3c/span\x3e\x3cspan class\x3d"cropper-point point-se" data-action\x3d"se"\x3e\x3c/span\x3e\x3c/div\x3e\x3c/div\x3e';
b=b.querySelector(".cropper-container");var l=b.querySelector(".cropper-canvas"),f=b.querySelector(".cropper-drag-box"),p=b.querySelector(".cropper-crop-box"),g=p.querySelector(".cropper-face");this.container=c;this.cropper=b;this.canvas=l;this.dragBox=f;this.cropBox=p;this.viewBox=b.querySelector(".cropper-view-box");this.face=g;l.appendChild(m);t(a,"cropper-hidden");c.insertBefore(b,a.nextSibling);this.isImg||C(m,"cropper-hide");this.initPreview();this.bind();e.aspectRatio=Math.max(0,e.aspectRatio)||
NaN;e.viewMode=Math.max(0,Math.min(3,Math.round(e.viewMode)))||0;t(p,"cropper-hidden");e.guides||t(p.getElementsByClassName("cropper-dashed"),"cropper-hidden");e.center||t(p.getElementsByClassName("cropper-center"),"cropper-hidden");e.background&&t(b,"cropper-bg");e.highlight||t(g,"cropper-invisible");e.cropBoxMovable&&(t(g,"cropper-move"),M(g,"action","all"));e.cropBoxResizable||(t(p.getElementsByClassName("cropper-line"),"cropper-hidden"),t(p.getElementsByClassName("cropper-point"),"cropper-hidden"));
this.render();this.ready=!0;this.setDragMode(e.dragMode);e.autoCrop&&this.crop();this.setData(e.data);q(e.ready)&&F(a,"ready",e.ready,{once:!0});K(a,"ready")}}},{key:"unbuild",value:function(){this.ready&&(this.ready=!1,this.unbind(),this.resetPreview(),this.cropper.parentNode.removeChild(this.cropper),C(this.element,"cropper-hidden"))}},{key:"uncreate",value:function(){var a=this.element;this.ready?(this.unbuild(),this.cropped=this.ready=!1):this.sizing?(this.sizingImage.onload=null,this.sized=this.sizing=
!1):this.reloading?this.xhr.abort():this.isImg?a.complete?clearTimeout(this.timeout):H(a,"load",this.onStart):this.image&&this.stop()}}],[{key:"noConflict",value:function(){window.Cropper=va;return a}},{key:"setDefaults",value:function(a){B(fa,f(a)&&a)}}]);return a}();B(T.prototype,{render:function(){this.initContainer();this.initCanvas();this.initCropBox();this.renderCanvas();this.cropped&&this.renderCropBox()},initContainer:function(){var a=this.element,d=this.options,e=this.container,m=this.cropper;
t(m,"cropper-hidden");C(a,"cropper-hidden");this.containerData=d={width:Math.max(e.offsetWidth,Number(d.minContainerWidth)||200),height:Math.max(e.offsetHeight,Number(d.minContainerHeight)||100)};v(m,{width:d.width,height:d.height});t(a,"cropper-hidden");C(m,"cropper-hidden")},initCanvas:function(){var a=this.containerData,d=this.imageData,e=this.options.viewMode,m=90===Math.abs(d.rotate)%180,c=m?d.naturalHeight:d.naturalWidth,b=m?d.naturalWidth:d.naturalHeight,l=c/b;m=a.width;var p=a.height;a.height*
l>a.width?3===e?m=a.height*l:p=a.width/l:3===e?p=a.width/l:m=a.height*l;c={aspectRatio:l,naturalWidth:c,naturalHeight:b,width:m,height:p};c.left=(a.width-m)/2;c.top=(a.height-p)/2;c.oldLeft=c.left;c.oldTop=c.top;this.canvasData=c;this.limited=1===e||2===e;this.limitCanvas(!0,!0);this.initialImageData=B({},d);this.initialCanvasData=B({},c)},limitCanvas:function(a,d){var e=this.options,m=this.containerData,c=this.canvasData,b=this.cropBoxData,l=e.viewMode,f=c.aspectRatio,g=this.cropped&&b;a&&(a=Number(e.minCanvasWidth)||
0,e=Number(e.minCanvasHeight)||0,1<l?(a=Math.max(a,m.width),e=Math.max(e,m.height),3===l&&(e*f>a?a=e*f:e=a/f)):0<l&&(a?a=Math.max(a,g?b.width:0):e?e=Math.max(e,g?b.height:0):g&&(a=b.width,e=b.height,e*f>a?a=e*f:e=a/f)),f=p({aspectRatio:f,width:a,height:e}),a=f.width,e=f.height,c.minWidth=a,c.minHeight=e,c.maxWidth=Infinity,c.maxHeight=Infinity);d&&(l?(d=m.width-c.width,f=m.height-c.height,c.minLeft=Math.min(0,d),c.minTop=Math.min(0,f),c.maxLeft=Math.max(0,d),c.maxTop=Math.max(0,f),g&&this.limited&&
(c.minLeft=Math.min(b.left,b.left+(b.width-c.width)),c.minTop=Math.min(b.top,b.top+(b.height-c.height)),c.maxLeft=b.left,c.maxTop=b.top,2===l&&(c.width>=m.width&&(c.minLeft=Math.min(0,d),c.maxLeft=Math.max(0,d)),c.height>=m.height&&(c.minTop=Math.min(0,f),c.maxTop=Math.max(0,f))))):(c.minLeft=-c.width,c.minTop=-c.height,c.maxLeft=m.width,c.maxTop=m.height))},renderCanvas:function(a,d){var e=this.canvasData,c=this.imageData;if(d){d=c.naturalWidth*Math.abs(c.scaleX||1);var b=c.naturalHeight*Math.abs(c.scaleY||
1);c=c.rotate||0;c=Math.abs(c)%180;if(90===c)b={width:b,height:d};else{var l=c%90*Math.PI/180,f=Math.sin(l),p=Math.cos(l);l=d*p+b*f;d=d*f+b*p;b=90<c?{width:d,height:l}:{width:l,height:d}}d=b.width;b=b.height;c=d/e.naturalWidth*e.width;f=b/e.naturalHeight*e.height;e.left-=(c-e.width)/2;e.top-=(f-e.height)/2;e.width=c;e.height=f;e.aspectRatio=d/b;e.naturalWidth=d;e.naturalHeight=b;this.limitCanvas(!0,!1)}if(e.width>e.maxWidth||e.width<e.minWidth)e.left=e.oldLeft;if(e.height>e.maxHeight||e.height<e.minHeight)e.top=
e.oldTop;e.width=Math.min(Math.max(e.width,e.minWidth),e.maxWidth);e.height=Math.min(Math.max(e.height,e.minHeight),e.maxHeight);this.limitCanvas(!1,!0);e.left=Math.min(Math.max(e.left,e.minLeft),e.maxLeft);e.top=Math.min(Math.max(e.top,e.minTop),e.maxTop);e.oldLeft=e.left;e.oldTop=e.top;v(this.canvas,B({width:e.width,height:e.height},O({translateX:e.left,translateY:e.top})));this.renderImage(a);this.cropped&&this.limited&&this.limitCropBox(!0,!0)},renderImage:function(a){var d=this.canvasData,e=
this.imageData,c=d.width/d.naturalWidth*e.naturalWidth,b=d.height/d.naturalHeight*e.naturalHeight;B(e,{width:c,height:b,left:(d.width-c)/2,top:(d.height-b)/2});v(this.image,B({width:e.width,height:e.height},O(B({translateX:e.left,translateY:e.top},e))));a&&this.output()},initCropBox:function(){var a=this.options,d=this.canvasData,e=a.aspectRatio;a=Number(a.autoCropArea)||.8;var c={width:d.width,height:d.height};e&&(d.height*e>d.width?c.height=c.width/e:c.width=c.height*e);this.cropBoxData=c;this.limitCropBox(!0,
!0);c.width=Math.min(Math.max(c.width,c.minWidth),c.maxWidth);c.height=Math.min(Math.max(c.height,c.minHeight),c.maxHeight);c.width=Math.max(c.minWidth,c.width*a);c.height=Math.max(c.minHeight,c.height*a);c.left=d.left+(d.width-c.width)/2;c.top=d.top+(d.height-c.height)/2;c.oldLeft=c.left;c.oldTop=c.top;this.initialCropBoxData=B({},c)},limitCropBox:function(a,d){var e=this.options,c=this.containerData,b=this.canvasData,l=this.cropBoxData,f=this.limited,p=e.aspectRatio;if(a){a=Number(e.minCropBoxWidth)||
0;e=Number(e.minCropBoxHeight)||0;var g=Math.min(c.width,f?b.width:c.width),n=Math.min(c.height,f?b.height:c.height);a=Math.min(a,c.width);e=Math.min(e,c.height);p&&(a&&e?e*p>a?e=a/p:a=e*p:a?e=a/p:e&&(a=e*p),n*p>g?n=g/p:g=n*p);l.minWidth=Math.min(a,g);l.minHeight=Math.min(e,n);l.maxWidth=g;l.maxHeight=n}d&&(f?(l.minLeft=Math.max(0,b.left),l.minTop=Math.max(0,b.top),l.maxLeft=Math.min(c.width,b.left+b.width)-l.width,l.maxTop=Math.min(c.height,b.top+b.height)-l.height):(l.minLeft=0,l.minTop=0,l.maxLeft=
c.width-l.width,l.maxTop=c.height-l.height))},renderCropBox:function(){var a=this.options,d=this.containerData,e=this.cropBoxData;if(e.width>e.maxWidth||e.width<e.minWidth)e.left=e.oldLeft;if(e.height>e.maxHeight||e.height<e.minHeight)e.top=e.oldTop;e.width=Math.min(Math.max(e.width,e.minWidth),e.maxWidth);e.height=Math.min(Math.max(e.height,e.minHeight),e.maxHeight);this.limitCropBox(!1,!0);e.left=Math.min(Math.max(e.left,e.minLeft),e.maxLeft);e.top=Math.min(Math.max(e.top,e.minTop),e.maxTop);e.oldLeft=
e.left;e.oldTop=e.top;a.movable&&a.cropBoxMovable&&M(this.face,"action",e.width>=d.width&&e.height>=d.height?"move":"all");v(this.cropBox,B({width:e.width,height:e.height},O({translateX:e.left,translateY:e.top})));this.cropped&&this.limited&&this.limitCanvas(!0,!0);this.disabled||this.output()},output:function(){this.preview();K(this.element,"crop",this.getData())}},{initPreview:function(){var a=this.crossOrigin,d=this.options.preview,e=a?this.crossOriginUrl:this.url,c=document.createElement("img");
a&&(c.crossOrigin=a);c.src=e;this.viewBox.appendChild(c);this.viewBoxImage=c;d&&(c=d,"string"===typeof d?c=this.element.ownerDocument.querySelectorAll(d):d.querySelector&&(c=[d]),this.previews=c,n(c,function(d){var c=document.createElement("img");M(d,"preview",{width:d.offsetWidth,height:d.offsetHeight,html:d.innerHTML});a&&(c.crossOrigin=a);c.src=e;c.style.cssText='display:block;width:100%;height:auto;min-width:0!important;min-height:0!important;max-width:none!important;max-height:none!important;image-orientation:0deg!important;"';
d.innerHTML="";d.appendChild(c)}))},resetPreview:function(){n(this.previews,function(a){var d=L(a,"preview");v(a,{width:d.width,height:d.height});a.innerHTML=d.html;G(a,"preview")})},preview:function(){var a=this.imageData,d=this.canvasData,e=this.cropBoxData,c=e.width,b=e.height,l=a.width,f=a.height,p=e.left-d.left-a.left,g=e.top-d.top-a.top;this.cropped&&!this.disabled&&(v(this.viewBoxImage,B({width:l,height:f},O(B({translateX:-p,translateY:-g},a)))),n(this.previews,function(d){var e=L(d,"preview"),
m=e.width;e=e.height;var r=m,u=e,n=1;c&&(n=m/c,u=b*n);b&&u>e&&(n=e/b,r=c*n,u=e);v(d,{width:r,height:u});v(d.getElementsByTagName("img")[0],B({width:l*n,height:f*n},O(B({translateX:-p*n,translateY:-g*n},a))))}))}},{bind:function(){var a=this.element,d=this.options,e=this.cropper;q(d.cropstart)&&F(a,"cropstart",d.cropstart);q(d.cropmove)&&F(a,"cropmove",d.cropmove);q(d.cropend)&&F(a,"cropend",d.cropend);q(d.crop)&&F(a,"crop",d.crop);q(d.zoom)&&F(a,"zoom",d.zoom);F(e,ca,this.onCropStart=this.cropStart.bind(this));
d.zoomable&&d.zoomOnWheel&&F(e,"wheel mousewheel DOMMouseScroll",this.onWheel=this.wheel.bind(this));d.toggleDragModeOnDblclick&&F(e,"dblclick",this.onDblclick=this.dblclick.bind(this));F(a.ownerDocument,da,this.onCropMove=this.cropMove.bind(this));F(a.ownerDocument,ea,this.onCropEnd=this.cropEnd.bind(this));d.responsive&&F(window,"resize",this.onResize=this.resize.bind(this))},unbind:function(){var a=this.element,d=this.options,e=this.cropper;q(d.cropstart)&&H(a,"cropstart",d.cropstart);q(d.cropmove)&&
H(a,"cropmove",d.cropmove);q(d.cropend)&&H(a,"cropend",d.cropend);q(d.crop)&&H(a,"crop",d.crop);q(d.zoom)&&H(a,"zoom",d.zoom);H(e,ca,this.onCropStart);d.zoomable&&d.zoomOnWheel&&H(e,"wheel mousewheel DOMMouseScroll",this.onWheel);d.toggleDragModeOnDblclick&&H(e,"dblclick",this.onDblclick);H(a.ownerDocument,da,this.onCropMove);H(a.ownerDocument,ea,this.onCropEnd);d.responsive&&H(window,"resize",this.onResize)}},{resize:function(){var a=this.options,d=this.container,e=this.containerData,c=Number(a.minContainerWidth)||
200,b=Number(a.minContainerHeight)||100;if(!(this.disabled||e.width<=c||e.height<=b)){var l=d.offsetWidth/e.width;if(1!==l||d.offsetHeight!==e.height){var f=void 0,p=void 0;a.restore&&(f=this.getCanvasData(),p=this.getCropBoxData());this.render();a.restore&&(this.setCanvasData(n(f,function(a,d){f[d]=a*l})),this.setCropBoxData(n(p,function(a,d){p[d]=a*l})))}}},dblclick:function(){this.disabled||"none"===this.options.dragMode||this.setDragMode(z(this.dragBox,"cropper-crop")?"move":"crop")},wheel:function(a){var d=
this,e=Number(this.options.wheelZoomRatio)||.1,c=1;this.disabled||(a.preventDefault(),this.wheeling||(this.wheeling=!0,setTimeout(function(){d.wheeling=!1},50),a.deltaY?c=0<a.deltaY?1:-1:a.wheelDelta?c=-a.wheelDelta/120:a.detail&&(c=0<a.detail?1:-1),this.zoom(-c*e,a)))},cropStart:function(a){if(!this.disabled){var d=this.options,e=this.pointers,b=void 0;a.changedTouches?n(a.changedTouches,function(a){e[a.identifier]=c(a)}):e[a.pointerId||0]=c(a);b=1<Object.keys(e).length&&d.zoomable&&d.zoomOnTouch?
"zoom":L(a.target,"action");qa.test(b)&&!1!==K(this.element,"cropstart",{originalEvent:a,action:b})&&(a.preventDefault(),this.action=b,this.cropping=!1,"crop"===b&&(this.cropping=!0,t(this.dragBox,"cropper-modal")))}},cropMove:function(a){var d=this.action;if(!this.disabled&&d){var e=this.pointers;a.preventDefault();!1!==K(this.element,"cropmove",{originalEvent:a,action:d})&&(a.changedTouches?n(a.changedTouches,function(a){B(e[a.identifier],c(a,!0))}):B(e[a.pointerId||0],c(a,!0)),this.change(a))}},
cropEnd:function(a){if(!this.disabled){var d=this.action,e=this.pointers;a.changedTouches?n(a.changedTouches,function(a){delete e[a.identifier]}):delete e[a.pointerId||0];d&&(a.preventDefault(),Object.keys(e).length||(this.action=""),this.cropping&&(this.cropping=!1,I(this.dragBox,"cropper-modal",this.cropped&&this.options.modal)),K(this.element,"cropend",{originalEvent:a,action:d}))}}},{change:function(a){var d=this.canvasData,e=this.containerData,c=this.cropBoxData,b=this.pointers,l=this.action,
f=this.options.aspectRatio,p=c.left,g=c.top,h=c.width,k=c.height,q=p+h,A=g+k,v=0,E=0,t=e.width,z=e.height,D=!0,y=void 0;!f&&a.shiftKey&&(f=h&&k?h/k:1);this.limited&&(v=c.minLeft,E=c.minTop,t=v+Math.min(e.width,d.width,d.left+d.width),z=E+Math.min(e.height,d.height,d.top+d.height));d=b[Object.keys(b)[0]];var x=d.endX-d.startX,w=d.endY-d.startY;y=function(a){switch(a){case "e":q+x>t&&(x=t-q);break;case "w":p+x<v&&(x=v-p);break;case "n":g+w<E&&(w=E-g);break;case "s":A+w>z&&(w=z-A)}};switch(l){case "all":p+=
x;g+=w;break;case "e":if(0<=x&&(q>=t||f&&(g<=E||A>=z))){D=!1;break}y("e");h+=x;f&&(k=h/f,g-=x/f/2);0>h&&(l="w",h=0);break;case "n":if(0>=w&&(g<=E||f&&(p<=v||q>=t))){D=!1;break}y("n");k-=w;g+=w;f&&(h=k*f,p+=w*f/2);0>k&&(l="s",k=0);break;case "w":if(0>=x&&(p<=v||f&&(g<=E||A>=z))){D=!1;break}y("w");h-=x;p+=x;f&&(k=h/f,g+=x/f/2);0>h&&(l="e",h=0);break;case "s":if(0<=w&&(A>=z||f&&(p<=v||q>=t))){D=!1;break}y("s");k+=w;f&&(h=k*f,p-=w*f/2);0>k&&(l="n",k=0);break;case "ne":if(f){if(0>=w&&(g<=E||q>=t)){D=!1;
break}y("n");k-=w;g+=w;h=k*f}else y("n"),y("e"),0<=x?q<t?h+=x:0>=w&&g<=E&&(D=!1):h+=x,0>=w?g>E&&(k-=w,g+=w):(k-=w,g+=w);0>h&&0>k?(l="sw",h=k=0):0>h?(l="nw",h=0):0>k&&(l="se",k=0);break;case "nw":if(f){if(0>=w&&(g<=E||p<=v)){D=!1;break}y("n");k-=w;g+=w;h=k*f;p+=w*f}else y("n"),y("w"),0>=x?p>v?(h-=x,p+=x):0>=w&&g<=E&&(D=!1):(h-=x,p+=x),0>=w?g>E&&(k-=w,g+=w):(k-=w,g+=w);0>h&&0>k?(l="se",h=k=0):0>h?(l="ne",h=0):0>k&&(l="sw",k=0);break;case "sw":if(f){if(0>=x&&(p<=v||A>=z)){D=!1;break}y("w");h-=x;p+=x;
k=h/f}else y("s"),y("w"),0>=x?p>v?(h-=x,p+=x):0<=w&&A>=z&&(D=!1):(h-=x,p+=x),0<=w?A<z&&(k+=w):k+=w;0>h&&0>k?(l="ne",h=k=0):0>h?(l="se",h=0):0>k&&(l="nw",k=0);break;case "se":if(f){if(0<=x&&(q>=t||A>=z)){D=!1;break}y("e");h+=x;k=h/f}else y("s"),y("e"),0<=x?q<t?h+=x:0<=w&&A>=z&&(D=!1):h+=x,0<=w?A<z&&(k+=w):k+=w;0>h&&0>k?(l="nw",h=k=0):0>h?(l="sw",h=0):0>k&&(l="ne",k=0);break;case "move":this.move(x,w);D=!1;break;case "zoom":this.zoom(S(b),a);D=!1;break;case "crop":x&&w?(y=N(this.cropper),p=d.startX-
y.left,g=d.startY-y.top,h=c.minWidth,k=c.minHeight,0<x?l=0<w?"se":"ne":0>x&&(p-=h,l=0<w?"sw":"nw"),0>w&&(g-=k),this.cropped||(C(this.cropBox,"cropper-hidden"),this.cropped=!0,this.limited&&this.limitCropBox(!0,!0))):D=!1}D&&(c.width=h,c.height=k,c.left=p,c.top=g,this.action=l,this.renderCropBox());n(b,function(a){a.startX=a.endX;a.startY=a.endY})}},{crop:function(){!this.ready||this.cropped||this.disabled||(this.cropped=!0,this.limitCropBox(!0,!0),this.options.modal&&t(this.dragBox,"cropper-modal"),
C(this.cropBox,"cropper-hidden"),this.setCropBoxData(this.initialCropBoxData));return this},reset:function(){this.ready&&!this.disabled&&(this.imageData=B({},this.initialImageData),this.canvasData=B({},this.initialCanvasData),this.cropBoxData=B({},this.initialCropBoxData),this.renderCanvas(),this.cropped&&this.renderCropBox());return this},clear:function(){this.cropped&&!this.disabled&&(B(this.cropBoxData,{left:0,top:0,width:0,height:0}),this.cropped=!1,this.renderCropBox(),this.limitCanvas(!0,!0),
this.renderCanvas(),C(this.dragBox,"cropper-modal"),t(this.cropBox,"cropper-hidden"));return this},replace:function(a){var d=1<arguments.length&&void 0!==arguments[1]?arguments[1]:!1;!this.disabled&&a&&(this.isImg&&(this.element.src=a),d?(this.url=a,this.image.src=a,this.ready&&(this.viewBoxImage.src=a,n(this.previews,function(d){d.getElementsByTagName("img")[0].src=a}))):(this.isImg&&(this.replaced=!0),this.options.data=null,this.uncreate(),this.load(a)));return this},enable:function(){this.ready&&
this.disabled&&(this.disabled=!1,C(this.cropper,"cropper-disabled"));return this},disable:function(){this.ready&&!this.disabled&&(this.disabled=!0,t(this.cropper,"cropper-disabled"));return this},destroy:function(){var a=this.element;if(!L(a,"cropper"))return this;this.isImg&&this.replaced&&(a.src=this.originalUrl);this.uncreate();G(a,"cropper");return this},move:function(a){var d=1<arguments.length&&void 0!==arguments[1]?arguments[1]:a,e=this.canvasData,c=e.left;e=e.top;return this.moveTo(k(a)?a:
c+Number(a),k(d)?d:e+Number(d))},moveTo:function(a){var d=1<arguments.length&&void 0!==arguments[1]?arguments[1]:a,e=this.canvasData,c=!1;a=Number(a);d=Number(d);this.ready&&!this.disabled&&this.options.movable&&(g(a)&&(e.left=a,c=!0),g(d)&&(e.top=d,c=!0),c&&this.renderCanvas(!0));return this},zoom:function(a,d){var c=this.canvasData;a=Number(a);return this.zoomTo(c.width*(0>a?1/(1-a):1+a)/c.naturalWidth,null,d)},zoomTo:function(a,d,c){var e=this.options,b=this.canvasData,p=b.width,h=b.height,k=b.naturalWidth,
n=b.naturalHeight;a=Number(a);if(0<=a&&this.ready&&!this.disabled&&e.zoomable){e=k*a;a*=n;if(!1===K(this.element,"zoom",{originalEvent:c,oldRatio:p/k,ratio:e/k}))return this;c?(k=this.pointers,d=N(this.cropper),c=k&&Object.keys(k).length?l(k):{pageX:c.pageX,pageY:c.pageY},b.left-=(c.pageX-d.left-b.left)/p*(e-p),b.top-=(c.pageY-d.top-b.top)/h*(a-h)):f(d)&&g(d.x)&&g(d.y)?(b.left-=(d.x-b.left)/p*(e-p),b.top-=(d.y-b.top)/h*(a-h)):(b.left-=(e-p)/2,b.top-=(a-h)/2);b.width=e;b.height=a;this.renderCanvas(!0)}return this},
rotate:function(a){return this.rotateTo((this.imageData.rotate||0)+Number(a))},rotateTo:function(a){a=Number(a);g(a)&&this.ready&&!this.disabled&&this.options.rotatable&&(this.imageData.rotate=a%360,this.renderCanvas(!0,!0));return this},scaleX:function(a){var d=this.imageData.scaleY;return this.scale(a,g(d)?d:1)},scaleY:function(a){var d=this.imageData.scaleX;return this.scale(g(d)?d:1,a)},scale:function(a){var d=1<arguments.length&&void 0!==arguments[1]?arguments[1]:a,c=this.imageData,b=!1;a=Number(a);
d=Number(d);this.ready&&!this.disabled&&this.options.scalable&&(g(a)&&(c.scaleX=a,b=!0),g(d)&&(c.scaleY=d,b=!0),b&&this.renderCanvas(!0,!0));return this},getData:function(){var a=0<arguments.length&&void 0!==arguments[0]?arguments[0]:!1,d=this.options,c=this.imageData,b=this.canvasData,l=this.cropBoxData,f=void 0;if(this.ready&&this.cropped){f={x:l.left-b.left,y:l.top-b.top,width:l.width,height:l.height};var p=c.width/c.naturalWidth;n(f,function(d,c){d/=p;f[c]=a?Math.round(d):d})}else f={x:0,y:0,
width:0,height:0};d.rotatable&&(f.rotate=c.rotate||0);d.scalable&&(f.scaleX=c.scaleX||1,f.scaleY=c.scaleY||1);return f},setData:function(a){var d=this.options,c=this.imageData,b=this.canvasData,l={};if(this.ready&&!this.disabled&&f(a)){var p=!1;d.rotatable&&g(a.rotate)&&a.rotate!==c.rotate&&(c.rotate=a.rotate,p=!0);d.scalable&&(g(a.scaleX)&&a.scaleX!==c.scaleX&&(c.scaleX=a.scaleX,p=!0),g(a.scaleY)&&a.scaleY!==c.scaleY&&(c.scaleY=a.scaleY,p=!0));p&&this.renderCanvas(!0,!0);d=c.width/c.naturalWidth;
g(a.x)&&(l.left=a.x*d+b.left);g(a.y)&&(l.top=a.y*d+b.top);g(a.width)&&(l.width=a.width*d);g(a.height)&&(l.height=a.height*d);this.setCropBoxData(l)}return this},getContainerData:function(){return this.ready?B({},this.containerData):{}},getImageData:function(){return this.sized?B({},this.imageData):{}},getCanvasData:function(){var a=this.canvasData,c={};this.ready&&n("left top width height naturalWidth naturalHeight".split(" "),function(d){c[d]=a[d]});return c},setCanvasData:function(a){var c=this.canvasData,
e=c.aspectRatio;this.ready&&!this.disabled&&f(a)&&(g(a.left)&&(c.left=a.left),g(a.top)&&(c.top=a.top),g(a.width)?(c.width=a.width,c.height=a.width/e):g(a.height)&&(c.height=a.height,c.width=a.height*e),this.renderCanvas(!0));return this},getCropBoxData:function(){var a=this.cropBoxData,c=void 0;this.ready&&this.cropped&&(c={left:a.left,top:a.top,width:a.width,height:a.height});return c||{}},setCropBoxData:function(a){var c=this.cropBoxData,e=this.options.aspectRatio,b=void 0,l=void 0;this.ready&&
this.cropped&&!this.disabled&&f(a)&&(g(a.left)&&(c.left=a.left),g(a.top)&&(c.top=a.top),g(a.width)&&a.width!==c.width&&(b=!0,c.width=a.width),g(a.height)&&a.height!==c.height&&(l=!0,c.height=a.height),e&&(b?c.height=c.width/e:l&&(c.width=c.height*e)),this.renderCropBox());return this},getCroppedCanvas:function(){var a=0<arguments.length&&void 0!==arguments[0]?arguments[0]:{};if(!this.ready||!window.HTMLCanvasElement)return null;var c=this.canvasData,e=E(this.image,this.imageData,c,a);if(!this.cropped)return e;
var b=this.getData(),l=b.x,f=b.y,g=b.width;b=b.height;c=e.width/Math.floor(c.naturalWidth);1!==c&&(l*=c,f*=c,g*=c,b*=c);var h=g/b,k=p({aspectRatio:h,width:a.maxWidth||Infinity,height:a.maxHeight||Infinity}),n=p({aspectRatio:h,width:a.minWidth||0,height:a.minHeight||0},"cover");h=p({aspectRatio:h,width:a.width||(1!==c?e.width:g),height:a.height||(1!==c?e.height:b)});c=h.width;h=h.height;c=Math.min(k.width,Math.max(n.width,c));h=Math.min(k.height,Math.max(n.height,h));k=document.createElement("canvas");
n=k.getContext("2d");k.width=A(c);k.height=A(h);n.fillStyle=a.fillColor||"transparent";n.fillRect(0,0,c,h);h=a.imageSmoothingEnabled;a=a.imageSmoothingQuality;n.imageSmoothingEnabled=void 0===h?!0:h;a&&(n.imageSmoothingQuality=a);a=e.width;h=e.height;var q=l,v=f,t=void 0,y=void 0,z=l=f=void 0,D=void 0;q<=-g||q>a?z=f=t=q=0:0>=q?(f=-q,q=0,z=t=Math.min(a,g+q)):q<=a&&(f=0,z=t=Math.min(g,a-q));0>=t||v<=-b||v>h?D=l=y=v=0:0>=v?(l=-v,v=0,D=y=Math.min(h,b+v)):v<=h&&(l=0,D=y=Math.min(b,h-v));b=[q,v,t,y];0<
z&&0<D&&(g=c/g,b.push(f*g,l*g,z*g,D*g));n.drawImage.apply(n,[e].concat(Y(b.map(function(a){return Math.floor(A(a))}))));return k},setAspectRatio:function(a){var c=this.options;this.disabled||k(a)||(c.aspectRatio=Math.max(0,a)||NaN,this.ready&&(this.initCropBox(),this.cropped&&this.renderCropBox()));return this},setDragMode:function(a){var c=this.options,e=this.dragBox,b=this.face;if(this.ready&&!this.disabled){var l="crop"===a,f=c.movable&&"move"===a;a=l||f?a:"none";c.dragMode=a;M(e,"action",a);I(e,
"cropper-crop",l);I(e,"cropper-move",f);c.cropBoxMovable||(M(b,"action",a),I(b,"cropper-crop",l),I(b,"cropper-move",f))}return this}});if(h.fn){var wa=h.fn.cropper;h.fn.cropper=function(a){for(var c=arguments.length,e=Array(1<c?c-1:0),b=1;b<c;b++)e[b-1]=arguments[b];var l=void 0;this.each(function(c,d){c=h(d);var b="destroy"===a,f=c.data("cropper");if(!f){if(b)return;f=h.extend({},c.data(),h.isPlainObject(a)&&a);f=new T(d,f);c.data("cropper",f)}"string"===typeof a&&(d=f[a],h.isFunction(d)&&(l=d.apply(f,
e),l===f&&(l=void 0),b&&c.removeData("cropper")))});return void 0!==l?l:this};h.fn.cropper.Constructor=T;h.fn.cropper.setDefaults=T.setDefaults;h.fn.cropper.noConflict=function(){h.fn.cropper=wa;return this}}})});
Module.define("htmlformat",["jquery"],function(h){function G(b){var h=[];g(b,h);h.forEach(function(b){for(var g=0;g<b.split.length;g+=2){var h=document.createTextNode(b.split[g]);b.parent.insertBefore(h,b.node);g+1<b.split.length&&b.parent.insertBefore(f("\x3ca/\x3e").text(b.split[g+1]).attr("href",b.prefix+b.split[g+1])[0],b.node)}});h.forEach(function(b){try{b.parent.removeChild(b.node)}catch(z){}})}function g(b,f){if("A"!==b.nodeName)for(var h=0;h<b.childNodes.length;++h){var k=b.childNodes[h];
if(3==k.nodeType){var n=k.nodeValue.split(/((?:\bhttps?:\/\/[-A-Z0-9+&@#\/%?=~_|!:,.;]*[-A-Z0-9+&@#\/%=~_|])|(?:\bwww\.[\S]+))/gim);1<n.length&&f.push({node:k,split:n,parent:k.parentNode,prefix:""})}else 1==k.nodeType&&g(k,f)}}function k(b){for(;b.attributes.length;)b.removeAttribute(b.attributes[0].name);return!0}function b(b,f){for(var g=b.attributes.length-1;0<=g;g--){var h=b.attributes[g],k=f[h.name];!0===k||"function"===typeof k&&k(h.value)||b.removeAttribute(h.name)}return!0}var f=jQuery,q=
this.defaults={brformat:!0,linkformat:!0,tags:{A:function(f){if(b(f,{href:function(b){return b.startsWith("http")||b.startsWith("https")||b.startsWith("/")}}))return f.setAttribute("rel","nofollow noindex"),!0},P:k,BR:k,STRONG:k,B:k,I:k,BLOCKQUOTE:k,SUB:k,SUP:k,STRIKE:k}};this.format=function(b,g){if(!b||!b.length)return"";g||(g=q);b=jQuery("\x3cdiv/\x3e").html(b);g.linkformat&&G(b[0]);b.find("*").each(function(){var b=g.tags[this.nodeName];"function"===typeof b&&b(this)||f(this).remove()});return g.brformat?
b.html().replace(/\n/g,"\x3cbr/\x3e"):b.html()}});
Module.define("jquery.payments",["jquery"],function(){(function(){var h,G=[].slice,g=[].indexOf||function(c){for(var b=0,f=this.length;b<f;b++)if(b in this&&this[b]===c)return b;return-1};var k=window.jQuery||window.Zepto||window.$;k.payment={};k.payment.fn={};k.fn.payment=function(){var c=arguments[0];var b=2<=arguments.length?G.call(arguments,1):[];return k.payment.fn[c].apply(this,b)};var b=/(\d{1,4})/g;k.payment.cards=h=[{type:"elo",patterns:[401178,401179,431274,438935,451416,457393,457631,457632,
504175,506699,5067,509,627780,636297,636368,650,6516,6550],format:b,length:[16],cvcLength:[3],luhn:!0},{type:"visaelectron",patterns:[4026,417500,4405,4508,4844,4913,4917],format:b,length:[16],cvcLength:[3],luhn:!0},{type:"maestro",patterns:[5018,502,503,506,56,58,639,6220,67],format:b,length:[12,13,14,15,16,17,18,19],cvcLength:[3],luhn:!0},{type:"forbrugsforeningen",patterns:[600],format:b,length:[16],cvcLength:[3],luhn:!0},{type:"dankort",patterns:[5019],format:b,length:[16],cvcLength:[3],luhn:!0},
{type:"visa",patterns:[4],format:b,length:[13,16],cvcLength:[3],luhn:!0},{type:"mastercard",patterns:[51,52,53,54,55,22,23,24,25,26,27],format:b,length:[16],cvcLength:[3],luhn:!0},{type:"amex",patterns:[34,37],format:/(\d{1,4})(\d{1,6})?(\d{1,5})?/,length:[15],cvcLength:[3,4],luhn:!0},{type:"dinersclub",patterns:[30,36,38,39],format:/(\d{1,4})(\d{1,6})?(\d{1,4})?/,length:[14],cvcLength:[3],luhn:!0},{type:"discover",patterns:[60,64,65,622],format:b,length:[16],cvcLength:[3],luhn:!0},{type:"unionpay",
patterns:[62,88],format:b,length:[16,17,18,19],cvcLength:[3],luhn:!1},{type:"jcb",patterns:[35],format:b,length:[16],cvcLength:[3],luhn:!0}];var f=function(c){var b,f;c=(c+"").replace(/\D/g,"");var g=0;for(b=h.length;g<b;g++){var k=h[g];var n=k.patterns;var q=0;for(f=n.length;q<f;q++){var y=n[q];y+="";if(c.substr(0,y.length)===y)return k}}};var q=function(c){var b;var f=0;for(b=h.length;f<b;f++){var g=h[f];if(g.type===c)return g}};var n=function(c){var b;var f=!0;var g=0;var h=(c+"").split("").reverse();
var k=0;for(b=h.length;k<b;k++){c=h[k];c=parseInt(c,10);if(f=!f)c*=2;9<c&&(c-=9);g+=c}return 0===g%10};var A=function(c){var b;return null!=c.prop("selectionStart")&&c.prop("selectionStart")!==c.prop("selectionEnd")||null!=("undefined"!==typeof document&&null!==document?null!=(b=document.selection)?b.createRange:void 0:void 0)&&document.selection.createRange().text?!0:!1};var v=function(c,b){try{var l=b.prop("selectionStart")}catch(Z){l=null}var f=b.val();b.val(c);if(null!==l&&b.is(":focus")){l===
f.length&&(l=c.length);if(f!==c){var g=f.slice(l-1,+l+1||9E9);f=c.slice(l-1,+l+1||9E9);c=c[l];/\d/.test(c)&&g===""+c+" "&&f===" "+c&&(l+=1)}b.prop("selectionStart",l);return b.prop("selectionEnd",l)}};var z=function(c){var b;null==c&&(c="");var f="";c=c.split("");var g=0;for(b=c.length;g<b;g++){var h=c[g];var k="０１２３４５６７８９".indexOf(h);-1<k&&(h="0123456789"[k]);f+=h}return f};var t=function(c){var b=k(c.currentTarget);return setTimeout(function(){var c=b.val();c=z(c);c=c.replace(/\D/g,"");return v(c,
b)})};var C=function(c){var b=k(c.currentTarget);return setTimeout(function(){var c=b.val();c=z(c);c=k.payment.formatCardNumber(c);return v(c,b)})};var I=function(c){var b=String.fromCharCode(c.which);if(/^\d+$/.test(b)){var g=k(c.currentTarget);var h=g.val();var n=f(h+b);var q=(h.replace(/\D/g,"")+b).length;var y=16;n&&(y=n.length[n.length.length-1]);if(!(q>=y||null!=g.prop("selectionStart")&&g.prop("selectionStart")!==h.length)){n=n&&"amex"===n.type?/^(\d{4}|\d{4}\s\d{6})$/:/(?:^|\s)(\d{4})$/;if(n.test(h))return c.preventDefault(),
setTimeout(function(){return g.val(h+" "+b)});if(n.test(h+b))return c.preventDefault(),setTimeout(function(){return g.val(h+b+" ")})}}};var y=function(c){var b=k(c.currentTarget);var f=b.val();if(8===c.which&&(null==b.prop("selectionStart")||b.prop("selectionStart")===f.length)){if(/\d\s$/.test(f))return c.preventDefault(),setTimeout(function(){return b.val(f.replace(/\d\s$/,""))});if(/\s\d?$/.test(f))return c.preventDefault(),setTimeout(function(){return b.val(f.replace(/\d$/,""))})}};var L=function(c){var b=
k(c.currentTarget);return setTimeout(function(){var c=b.val();c=z(c);c=k.payment.formatExpiry(c);return v(c,b)})};var M=function(c){var b=String.fromCharCode(c.which);if(/^\d+$/.test(b)){var f=k(c.currentTarget);var g=f.val()+b;if(/^\d$/.test(g)&&"0"!==g&&"1"!==g)return c.preventDefault(),setTimeout(function(){return f.val("0"+g+" / ")});if(/^\d\d$/.test(g))return c.preventDefault(),setTimeout(function(){var c=parseInt(g[0],10);var b=parseInt(g[1],10);return 2<b&&0!==c?f.val("0"+c+" / "+b):f.val(""+
g+" / ")})}};var U=function(c){var b=String.fromCharCode(c.which);if(/^\d+$/.test(b)&&(c=k(c.currentTarget),b=c.val(),/^\d\d$/.test(b)))return c.val(""+b+" / ")};var H=function(c){var b=String.fromCharCode(c.which);if("/"===b||" "===b)if(c=k(c.currentTarget),b=c.val(),/^\d$/.test(b)&&"0"!==b)return c.val("0"+b+" / ")};var F=function(c){var b=k(c.currentTarget);var f=b.val();if(8===c.which&&(null==b.prop("selectionStart")||b.prop("selectionStart")===f.length)&&/\d\s\/\s$/.test(f))return c.preventDefault(),
setTimeout(function(){return b.val(f.replace(/\d\s\/\s$/,""))})};var K=function(c){var b=k(c.currentTarget);return setTimeout(function(){var c=b.val();c=z(c);c=c.replace(/\D/g,"").slice(0,4);return v(c,b)})};var N=function(c){if(c.metaKey||c.ctrlKey)return!0;if(32===c.which)return!1;if(0===c.which||33>c.which)return!0;c=String.fromCharCode(c.which);return!!/[\d\s]/.test(c)};var Q=function(c){var b=k(c.currentTarget);c=String.fromCharCode(c.which);if(/^\d+$/.test(c)&&!A(b))return c=(b.val()+c).replace(/\D/g,
""),(b=f(c))?c.length<=b.length[b.length.length-1]:16>=c.length};var R=function(c){var b=k(c.currentTarget);c=String.fromCharCode(c.which);if(/^\d+$/.test(c)&&!A(b)&&(b=b.val()+c,b=b.replace(/\D/g,""),6<b.length))return!1};var O=function(c){var b=k(c.currentTarget);c=String.fromCharCode(c.which);if(/^\d+$/.test(c)&&!A(b))return 4>=(b.val()+c).length};var S=function(c){c=k(c.currentTarget);var b=c.val();var f=k.payment.cardType(b)||"unknown";if(!c.hasClass(f)){var g;var n=[];var q=0;for(g=h.length;q<
g;q++)b=h[q],n.push(b.type);c.removeClass("unknown");c.removeClass(n.join(" "));c.addClass(f);c.toggleClass("identified","unknown"!==f);return c.trigger("payment.cardType",f)}};k.payment.fn.formatCardCVC=function(){this.on("keypress",N);this.on("keypress",O);this.on("paste",K);this.on("change",K);this.on("input",K);return this};k.payment.fn.formatCardExpiry=function(){this.on("keypress",N);this.on("keypress",R);this.on("keypress",M);this.on("keypress",H);this.on("keypress",U);this.on("keydown",F);
this.on("change",L);this.on("input",L);return this};k.payment.fn.formatCardNumber=function(){this.on("keypress",N);this.on("keypress",Q);this.on("keypress",I);this.on("keydown",y);this.on("keyup",S);this.on("paste",C);this.on("change",C);this.on("input",C);this.on("input",S);return this};k.payment.fn.restrictNumeric=function(){this.on("keypress",N);this.on("paste",t);this.on("change",t);this.on("input",t);return this};k.payment.fn.cardExpiryVal=function(){return k.payment.cardExpiryVal(k(this).val())};
k.payment.cardExpiryVal=function(c){var b=c.split(/[\s\/]+/,2);c=b[0];var f=b[1];2===(null!=f?f.length:void 0)&&/^\d+$/.test(f)&&(b=(new Date).getFullYear(),b=b.toString().slice(0,2),f=b+f);c=parseInt(c,10);f=parseInt(f,10);return{month:c,year:f}};k.payment.validateCardNumber=function(c){var b,h;c=(c+"").replace(/\s+|-/g,"");return/^\d+$/.test(c)?(b=f(c))?(h=c.length,0<=g.call(b.length,h))&&(!1===b.luhn||n(c)):!1:!1};k.payment.validateCardExpiry=function(c,b){"object"===typeof c&&"month"in c&&(b=
c,c=b.month,b=b.year);if(!c||!b)return!1;c=k.trim(c);b=k.trim(b);if(!(/^\d+$/.test(c)&&/^\d+$/.test(b)&&1<=c&&12>=c))return!1;2===b.length&&(b=70>b?"20"+b:"19"+b);if(4!==b.length)return!1;b=new Date(b,c);c=new Date;b.setMonth(b.getMonth()-1);b.setMonth(b.getMonth()+1,1);return b>c};k.payment.validateCardCVC=function(c,b){var f;c=k.trim(c);if(!/^\d+$/.test(c))return!1;b=q(b);return null!=b?(f=c.length,0<=g.call(b.cvcLength,f)):3<=c.length&&4>=c.length};k.payment.cardType=function(c){var b;return c?
(null!=(b=f(c))?b.type:void 0)||null:null};k.payment.formatCardNumber=function(c){var b;c=c.replace(/\D/g,"");var g=f(c);if(!g)return c;c=c.slice(0,g.length[g.length.length-1]);if(g.format.global)return null!=(b=c.match(g.format))?b.join(" "):void 0;c=g.format.exec(c);if(null!=c)return c.shift(),c=k.grep(c,function(b){return b}),c.join(" ")};k.payment.formatExpiry=function(b){var c=b.match(/^\D*(\d{1,2})(\D+)?(\d{1,4})?/);if(!c)return"";b=c[1]||"";var f=c[2]||"";c=c[3]||"";0<c.length?f=" / ":" /"===
f?(b=b.substring(0,1),f=""):2===b.length||0<f.length?f=" / ":1===b.length&&"0"!==b&&"1"!==b&&(b="0"+b,f=" / ");return b+f+c}}).call(this)});
Module.define("jquery.whenall",["jquery"],function(){(function(h){var G=[].slice;h.whenAll=function(g){function k(f,g,h){return function(){h!==b&&v++;n.notifyWith(g[f]=this,h[f]=G.call(arguments));if(!--q)n[(v?"reject":"resolve")+"With"](g,h)}}for(var b=1==arguments.length&&h.isArray(g)?g:G.call(arguments),f=b.length,q=f,n=h.Deferred(),A=0,v=0,z=Array(f),t=Array(f),C=Array(f),I;A<f;A++)(I=b[A])&&h.isFunction(I.promise)?I.promise().done(k(A,C,b)).fail(k(A,z,t)):(n.notifyWith(this,I),--q);q||n.resolveWith(C,
b);return n.promise()}})(jQuery)});
Module.define("timepicker",["jquery","timepicker.css"],function(){(function(h,G,g){var k=function(b,f){this.$element=h(b);this.defaultTime=f.defaultTime;this.disableFocus=f.disableFocus;this.disableMousewheel=f.disableMousewheel;this.isOpen=f.isOpen;this.minuteStep=f.minuteStep;this.modalBackdrop=f.modalBackdrop;this.orientation=f.orientation;this.secondStep=f.secondStep;this.snapToStep=f.snapToStep;this.showInputs=f.showInputs;this.showMeridian=f.showMeridian;this.showSeconds=f.showSeconds;this.maxHours=
f.maxHours;this.explicitMode=f.explicitMode;this._init()};k.prototype={constructor:k,_init:function(){this.$element.on({"focus.timepicker":h.proxy(this.highlightUnit,this),"click.timepicker":h.proxy(this.highlightUnit,this),"keydown.timepicker":h.proxy(this.elementKeydown,this),"blur.timepicker":h.proxy(this.blurElement,this),"mousewheel.timepicker DOMMouseScroll.timepicker":h.proxy(this.mousewheel,this)});this.setDefaultTime(this.defaultTime)},blurElement:function(){this.highlightedUnit=null;this.updateFromElementVal()},
clear:function(){this.meridian=this.second=this.minute=this.hour="";this.$element.val("")},decrementHour:function(){if(this.showMeridian)if(1===this.hour)this.hour=12;else{if(12===this.hour)return this.hour--,this.toggleMeridian();if(0===this.hour)return this.hour=11,this.toggleMeridian();this.hour--}else 0>=this.hour?this.hour=this.maxHours-1:this.hour--},decrementMinute:function(b){b=b?this.minute-b:this.minute-this.minuteStep;0>b?(this.decrementHour(),this.minute=b+60):this.minute=b},decrementSecond:function(){var b=
this.second-this.secondStep;0>b?(this.decrementMinute(!0),this.second=b+60):this.second=b},elementKeydown:function(b){switch(b.which){case 9:if(b.shiftKey){if("hour"===this.highlightedUnit)break;this.highlightPrevUnit()}else if(this.showMeridian&&"meridian"===this.highlightedUnit||this.showSeconds&&"second"===this.highlightedUnit||!this.showMeridian&&!this.showSeconds&&"minute"===this.highlightedUnit)break;else this.highlightNextUnit();b.preventDefault();this.updateFromElementVal();break;case 27:this.updateFromElementVal();
break;case 37:b.preventDefault();this.highlightPrevUnit();this.updateFromElementVal();break;case 38:b.preventDefault();switch(this.highlightedUnit){case "hour":this.incrementHour();this.highlightHour();break;case "minute":this.incrementMinute();this.highlightMinute();break;case "second":this.incrementSecond();this.highlightSecond();break;case "meridian":this.toggleMeridian(),this.highlightMeridian()}this.update();break;case 39:b.preventDefault();this.highlightNextUnit();this.updateFromElementVal();
break;case 40:b.preventDefault();switch(this.highlightedUnit){case "hour":this.decrementHour();this.highlightHour();break;case "minute":this.decrementMinute();this.highlightMinute();break;case "second":this.decrementSecond();this.highlightSecond();break;case "meridian":this.toggleMeridian(),this.highlightMeridian()}this.update()}},getCursorPosition:function(){var b=this.$element.get(0);if("selectionStart"in b)return b.selectionStart;if(g.selection){b.focus();var f=g.selection.createRange(),h=g.selection.createRange().text.length;
f.moveStart("character",-b.value.length);return f.text.length-h}},getTime:function(){return""===this.hour?"":this.hour+":"+(1===this.minute.toString().length?"0"+this.minute:this.minute)+(this.showSeconds?":"+(1===this.second.toString().length?"0"+this.second:this.second):"")+(this.showMeridian?" "+this.meridian:"")},highlightUnit:function(){this.position=this.getCursorPosition();0<=this.position&&2>=this.position?this.highlightHour():3<=this.position&&5>=this.position?this.highlightMinute():6<=this.position&&
8>=this.position?this.showSeconds?this.highlightSecond():this.highlightMeridian():9<=this.position&&11>=this.position&&this.highlightMeridian()},highlightNextUnit:function(){switch(this.highlightedUnit){case "hour":this.highlightMinute();break;case "minute":this.showSeconds?this.highlightSecond():this.showMeridian?this.highlightMeridian():this.highlightHour();break;case "second":this.showMeridian?this.highlightMeridian():this.highlightHour();break;case "meridian":this.highlightHour()}},highlightPrevUnit:function(){switch(this.highlightedUnit){case "hour":this.showMeridian?
this.highlightMeridian():this.showSeconds?this.highlightSecond():this.highlightMinute();break;case "minute":this.highlightHour();break;case "second":this.highlightMinute();break;case "meridian":this.showSeconds?this.highlightSecond():this.highlightMinute()}},highlightHour:function(){var b=this.$element.get(0),f=this;this.highlightedUnit="hour";b.setSelectionRange&&setTimeout(function(){10>f.hour?b.setSelectionRange(0,1):b.setSelectionRange(0,2)},0)},highlightMinute:function(){var b=this.$element.get(0),
f=this;this.highlightedUnit="minute";b.setSelectionRange&&setTimeout(function(){10>f.hour?b.setSelectionRange(2,4):b.setSelectionRange(3,5)},0)},highlightSecond:function(){var b=this.$element.get(0),f=this;this.highlightedUnit="second";b.setSelectionRange&&setTimeout(function(){10>f.hour?b.setSelectionRange(5,7):b.setSelectionRange(6,8)},0)},highlightMeridian:function(){var b=this.$element.get(0),f=this;this.highlightedUnit="meridian";b.setSelectionRange&&(this.showSeconds?setTimeout(function(){10>
f.hour?b.setSelectionRange(8,10):b.setSelectionRange(9,11)},0):setTimeout(function(){10>f.hour?b.setSelectionRange(5,7):b.setSelectionRange(6,8)},0))},incrementHour:function(){if(this.showMeridian){if(11===this.hour)return this.hour++,this.toggleMeridian();12===this.hour&&(this.hour=0)}this.hour===this.maxHours-1?this.hour=0:this.hour++},incrementMinute:function(b){b=b?this.minute+b:this.minute+this.minuteStep-this.minute%this.minuteStep;59<b?(this.incrementHour(),this.minute=b-60):this.minute=b},
incrementSecond:function(){var b=this.second+this.secondStep-this.second%this.secondStep;59<b?(this.incrementMinute(!0),this.second=b-60):this.second=b},mousewheel:function(b){if(!this.disableMousewheel){b.preventDefault();b.stopPropagation();var f=b.originalEvent.wheelDelta||-b.originalEvent.detail,g=null;"mousewheel"===b.type?g=-1*b.originalEvent.wheelDelta:"DOMMouseScroll"===b.type&&(g=40*b.originalEvent.detail);g&&(b.preventDefault(),h(this).scrollTop(g+h(this).scrollTop()));switch(this.highlightedUnit){case "minute":0<
f?this.incrementMinute():this.decrementMinute();this.highlightMinute();break;case "second":0<f?this.incrementSecond():this.decrementSecond();this.highlightSecond();break;case "meridian":this.toggleMeridian();this.highlightMeridian();break;default:0<f?this.incrementHour():this.decrementHour(),this.highlightHour()}return!1}},changeToNearestStep:function(b,f){return 0===b%f?b:Math.round(b%f/f)?(b+(f-b%f))%60:b-b%f},remove:function(){h("document").off(".timepicker");delete this.$element.data().timepicker},
setDefaultTime:function(b){if(this.$element.val())this.updateFromElementVal();else if("current"===b){b=new Date;var f=b.getHours(),g=b.getMinutes(),h=b.getSeconds(),k="AM";0!==h&&(h=Math.ceil(b.getSeconds()/this.secondStep)*this.secondStep,60===h&&(g+=1,h=0));0!==g&&(g=Math.ceil(b.getMinutes()/this.minuteStep)*this.minuteStep,60===g&&(f+=1,g=0));this.showMeridian&&(0===f?f=12:12<=f?(12<f&&(f-=12),k="PM"):k="AM");this.hour=f;this.minute=g;this.second=h;this.meridian=k;this.update()}else!1===b?(this.second=
this.minute=this.hour=0,this.meridian="AM"):this.setTime(b)},setTime:function(b){if(b){if("object"===typeof b&&b.getMonth){var f=b.getHours();var g=b.getMinutes();b=b.getSeconds();if(this.showMeridian){var h="AM";12<f&&(h="PM",f%=12);12===f&&(h="PM")}}else{var k=(/a/i.test(b)?1:0)+(/p/i.test(b)?2:0);if(2<k){this.clear();return}b=b.replace(/[^0-9:]/g,"").split(":");f=b[0]?b[0].toString():b.toString();if(this.explicitMode&&2<f.length&&0!==f.length%2){this.clear();return}g=b[1]?b[1].toString():"";b=
b[2]?b[2].toString():"";4<f.length&&(b=f.slice(-2),f=f.slice(0,-2));2<f.length&&(g=f.slice(-2),f=f.slice(0,-2));2<g.length&&(b=g.slice(-2),g=g.slice(0,-2));f=parseInt(f,10);g=parseInt(g,10);b=parseInt(b,10);isNaN(f)&&(f=0);isNaN(g)&&(g=0);isNaN(b)&&(b=0);59<b&&(b=59);59<g&&(g=59);f>=this.maxHours&&(f=this.maxHours-1);if(this.showMeridian)12<f&&(k=2,f-=12),k||(k=1),0===f&&(f=12),h=1===k?"AM":"PM";else if(12>f&&2===k)f+=12;else if(f>=this.maxHours)f=this.maxHours-1;else if(0>f||12===f&&1===k)f=0}this.hour=
f;this.snapToStep?(this.minute=this.changeToNearestStep(g,this.minuteStep),this.second=this.changeToNearestStep(b,this.secondStep)):(this.minute=g,this.second=b);this.meridian=h;this.update()}else this.clear()},toggleMeridian:function(){this.meridian="AM"===this.meridian?"PM":"AM"},update:function(){this.updateElement();this.$element.trigger({type:"changeTime.timepicker",time:{value:this.getTime(),hours:this.hour,minutes:this.minute,seconds:this.second,meridian:this.meridian}})},updateElement:function(){this.$element.val(this.getTime()).change()},
updateFromElementVal:function(){this.setTime(this.$element.val())}};h.fn.timepicker=function(b){var f=Array.apply(null,arguments);f.shift();return this.each(function(){var g=h(this),n=g.data("timepicker"),A="object"===typeof b&&b;n||g.data("timepicker",n=new k(this,h.extend({},h.fn.timepicker.defaults,A,h(this).data())));"string"===typeof b&&n[b].apply(n,f)})};h.fn.timepicker.defaults={defaultTime:"current",disableFocus:!1,disableMousewheel:!1,isOpen:!1,minuteStep:15,modalBackdrop:!1,orientation:{x:"auto",
y:"auto"},secondStep:15,snapToStep:!1,showSeconds:!1,showInputs:!0,showMeridian:!0,maxHours:24,explicitMode:!1};h.fn.timepicker.Constructor=k;h(g).on("focus.timepicker.data-api click.timepicker.data-api",'[data-provide\x3d"timepicker"]',function(b){var f=h(this);f.data("timepicker")||(b.preventDefault(),f.timepicker())})})(jQuery,window,document)});
Module.define("waitforimages",["jquery"],function(){var h=jQuery,G=function(g){return g.srcset&&g.sizes}(new Image);h.waitForImages={hasImageProperties:["backgroundImage","listStyleImage","borderImage","borderCornerImage","cursor"],hasImageAttributes:["srcset"]};h.expr.pseudos["has-src"]=function(g){return h(g).is('img[src][src!\x3d""]')};h.expr.pseudos.uncached=function(g){return h(g).is(":has-src")?!g.complete:!1};h.fn.waitForImages=function(){var g=0,k=0,b=h.Deferred(),f=this,q=[],n=h.waitForImages.hasImageProperties||
[],A=h.waitForImages.hasImageAttributes||[],v=/url\(\s*(['"]?)(.*?)\1\s*\)/g;if(h.isPlainObject(arguments[0])){var z=arguments[0].waitForAll;var t=arguments[0].each;var C=arguments[0].finished}else 1===arguments.length&&"boolean"===h.type(arguments[0])?z=arguments[0]:(C=arguments[0],t=arguments[1],z=arguments[2]);C=C||h.noop;t=t||h.noop;z=!!z;if(!h.isFunction(C)||!h.isFunction(t))throw new TypeError("An invalid callback was supplied.");this.each(function(){var b=h(this);z?b.find("*").addBack().each(function(){var b=
h(this);b.is("img:has-src")&&!b.is("[srcset]")&&q.push({src:b.attr("src"),element:b[0]});h.each(n,function(f,g){f=b.css(g);if(!f)return!0;for(;g=v.exec(f);)q.push({src:g[2],element:b[0]})});h.each(A,function(f,g){if(!b.attr(g))return!0;q.push({src:b.attr("src"),srcset:b.attr("srcset"),element:b[0]})})}):b.find("img:has-src").each(function(){q.push({src:this.src,element:this})})});g=q.length;k=0;0===g&&(C.call(f),b.resolveWith(f));h.each(q,function(n,q){n=new Image;h(n).one("load.waitForImages error.waitForImages",
function U(n){n=[k,g,"load"==n.type];k++;t.apply(q.element,n);b.notifyWith(q.element,n);h(this).off("load.waitForImages error.waitForImages",U);if(k==g)return C.call(f[0]),b.resolveWith(f[0]),!1});G&&q.srcset&&(n.srcset=q.srcset,n.sizes=q.sizes);n.src=q.src});return b.promise()}});